#cloud-config
runcmd:
  - apt-get update
  - apt-get install -y sudo apt-get install mysql-client-core-5.7
  - apt-get install -y git
  - apt-get install -y python3-setuptools
  - git clone https://github.com/s3tools/s3cmd.git
  - cd s3cmd && python3 setup.py install
  - apt-get update
  - cd / && git clone https://github.com/svarn-ivise/worker.git
#  - "ACCESS_KEY=spaces.key \
#    SECRET_KEY=spaces.secret \
#    LOCATION=spaces.loc \
#    bash -c '/usr/bin/envsubst < /api/template.s3cfg > /root/.s3cfg'"
#  - sudo mkdir /models/
#  - sudo s3cmd get s3://modelstorage/rf.rds /models/rf.rds
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
#  - sudo mkdir -p /storage/docker/mysql-datadir
#  - sudo cd /api
#  - sudo docker-compose up --scale api=4